// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

type Mint struct {
	BlockNum          int32          `json:"block_num"`
	CollectionAddress string         `json:"collection_address"`
	TokenID           string         `json:"token_id"`
	TokenUrl          sql.NullString `json:"token_url"`
	TokenName         sql.NullString `json:"token_name"`
	ImageUrl          sql.NullString `json:"image_url"`
	ImageData         sql.NullString `json:"image_data"`
}
